#!/bin/zsh
# See: https://github.com/pr3d4t0r/aoc2020/blob/0001-AoC-day-2/LICENSE
# vim: set fileencoding=utf-8:


# *** constants ***

CODE_DIR="./aoc"
DATA_DIR="./resources"
PROGRAM_TEMPLATE="$DATA_DIR/templates/prog-template.py"
TEST_DATA_DIR="$DATA_DIR/test"
TEST_DIR="./test"
UNIT_TEST_TEMPLATE="$DATA_DIR/templates/test-template.py"


# *** functions ***

function die {
    echo "$1"
    exit "$2"
} # die


function assertProgramNameIn {
    local programName="$1"

    [[ -n "$programName" ]] || die "please provide a valid program name (no extension)", "1"
} # assertProgramNameIn


function initCodeFor {
    local programName

    programName="$CODE_DIR/$1.py"
    day=$(date +%d)

    cat "$PROGRAM_TEMPLATE" | awk -v "d=$day" 'BEGIN { gsub("0", "", d); } { gsub("%d%", d); print; }' > "$programName"
    echo "-- initialized: $programName"
} # initCodeFor


function updateMakefileWith {
    local tmpMakefile=$(mktemp)

    cat Makefile| awk -v "p=$1" '{ if (index($0, "test:")) b = 1; if (b && index($0, "pip uninstall")) { printf("\tpytest -v %s\n", p); b = 0; } print; }' > "$tmpMakefile"
    cat "$tmpMakefile" > Makefile
    rm -f "$tmpMakefile"

    echo "-- Makefile updated"
} # updateMakefileWith


function initUnitTestsFor {
    local unitTest
    local progName="$1"

    unitTest="$TEST_DIR/test-$1.py"

    cat "$UNIT_TEST_TEMPLATE" | awk -v "t=$progName" 'BEGIN { tU=toupper(t); } { gsub("%t%", t); gsub("%T%", tU); print; }' > "$unitTest"

    echo "-- initialized: $unitTest"

    updateMakefileWith "$unitTest"
} # initUnitTestsFor


function initDataFilesFor {
    local dataFile
    local programName="$1"
    local testDataFile

    dataFile="$DATA_DIR/$programName-data.txt"
    testDataFile="$TEST_DATA_DIR/$programName-test-data.txt"

    touch "$dataFile" "$testDataFile"

    echo "-- initialized: $dataFile"
    echo "-- initialized: $testDataFile"
} # initDataFilesFor


# +++ main +++

assertProgramNameIn "$1"
programName="$1"

initCodeFor "$programName"
initUnitTestsFor "$programName"
initDataFilesFor "$programName"

# cat $(grep -lr "TODO:" . | awk '!/site-packages/ && !/\.swp/ && !/-template/ && !/aocgen/') | awk '/TODO:/'
echo '-- done!'

